[general]
import = [
	"~/.config/alacritty/themes/themes/custom_bae.toml"
]

[window]

opacity = 0.685

padding.x = 10
padding.y = 10

decorations = "FUll"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "Fira Code"
bold.family = "Fira Code"
italic.family = "Fira Code"
bold_italic.family = "Fira Code"

size = 10.0
